-- DROP DATABASE IF EXISTS ridemyway;

-- CREATE DATABASE ridemyway;
DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	firstname VARCHAR NOT NULL,
	lastname VARCHAR NOT NULL,
	email VARCHAR NOT NULL,
	telephone text NOT NULL,
	password VARCHAR  NOT NULL,
	createdAt timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
)